CREATE TABLE EmployeesNew(
	EmpId int primary key identity(1,1),
	EmpName varchar(100),	
	City varchar(30),
	Salary money,
	DOJ datetime
)



INSERT INTO EmployeesNew(EmpName,CITY,Salary,DOJ) VALUES
('SAM','NYC',45000,NULL),
('AMAN','DELHI',30000,'2022-01-04'),
('JAY','CHENNAI',40000,'2023-05-12'),
('AMANDA','SYDNEY',60000,NULL)

SELECT * FROM EmployeesNew
FOR JSON PATH

SELECT * FROM EmployeesNew
FOR JSON PATH,ROOT('EMPLOYEES')

SELECT * FROM EmployeesNew
FOR JSON PATH, INCLUDE_NULL_VALUES

SELECT * FROM EmployeesNew
FOR JSON PATH,ROOT('EMPLOYEES'),INCLUDE_NULL_VALUES

SELECT * FROM EmployeesNew
FOR JSON PATH,WITHOUT_ARRAY_WRAPPER

SELECT * FROM EmployeesNew
FOR JSON PATH,WITHOUT_ARRAY_WRAPPER,INCLUDE_NULL_VALUES

SELECT EmpId,EmpName,DOJ FROM EmployeesNew
FOR JSON PATH,WITHOUT_ARRAY_WRAPPER

SELECT 1 AS EMPID, 'JOHN' AS EMPNAME
FOR JSON PATH

SELECT * FROM EmployeesNew
FOR JSON AUTO

