SELECT GETDATE()--RETURNS THE DATE

SELECT SYSDATETIME()--RETURN DATE WITH MILISECONDS

SELECT SYSUTCDATETIME()--RETURN DATE WITH MILISECONDS IN UTC TIME

--HOW WE ENTER DATES
SELECT '2025-12-30'

SELECT DATEFROMPARTS(2025,12,30)

SELECT DATETIMEFROMPARTS(2025,12,30,10,13,20,34)

--EXTRACT DIFFERENT COMPONENTS OF A DATE
SELECT YEAR(DATEFROMPARTS(2025,12,30))

SELECT BirthDate, YEAR(BirthDate) FROM DimEmployee

SELECT MONTH(DATEFROMPARTS(2025,12,30))

SELECT BirthDate, MONTH(BirthDate) FROM DimEmployee

SELECT DAY(DATEFROMPARTS(2025,12,30))

SELECT BirthDate, DAY(BirthDate) FROM DimEmployee

SELECT DATEPART(YYYY,GETDATE())

SELECT DATEPART(MM,GETDATE())

SELECT DATEPART(DD,GETDATE())

SELECT DATEPART(WEEKDAY,GETDATE())

SELECT DATENAME(MM,GETDATE())

SELECT DATENAME(WEEKDAY,GETDATE())--RETURNS NAME INSTEAD OF INTEGERS

SELECT FORMAT(GETDATE(),'yy')
SELECT FORMAT(GETDATE(),'yyyy')

SELECT FORMAT(GETDATE(),'dd')
SELECT FORMAT(GETDATE(),'ddd')

SELECT FORMAT(GETDATE(),'MM')
SELECT FORMAT(GETDATE(),'MMM')

SELECT FORMAT(GETDATE(),'yyy-MMM-ddd hh:mm:ss')


SELECT DATEADD(YEAR,1,GETDATE())

SELECT DATEADD(MM,1,GETDATE())--ADD ON THE DATE

SELECT DATEDIFF(YEAR,DATEFROMPARTS(2004,06,11),GETDATE())

SELECT EOMONTH(GETDATE(),1)

SELECT EOMONTH(GETDATE(),0)

SELECT EOMONTH(GETDATE(),-1)

SELECT EOMONTH(GETDATE(),4)
