DELETE FROM DIMProductBKUP--DELETE EVERY ROW

DELETE FROM DIMProductBKUP
WHERE COLOR='RED'

TRUNCATE TABLE DIMProductBKUP--DELETE ALL THE ROWS AND CANNOT BE USED TO FILTER SPECIFIC ROWS USING WHERE

--DELETE DOES NOT RESET THE IDENTITY BACK  TO THE ORIGINAL BUT TRUNCATE DOES