SELECT * FROM tblEmps
UNION
SELECT * FROM tblEmps2

SELECT * FROM tblEmps
INTERSECT
SELECT * FROM tblEmps2

--INTERSECT GIVES YOU THE MATCHING ROWS BTWN THE TABLES 

DELETE FROM tblEmps2 WHERE EMPLOYEEID=10

