SELECT * FROM EMPLOYEES
SELECT * INTO EMPLOYEES_STAGE FROM EMPLOYEES

DELETE FROM EMPLOYEES WHERE EmployeeId>6

UPDATE EMPLOYEES_STAGE SET Salary = 34000
WHERE EmployeeId = 9

UPDATE EMPLOYEES_STAGE SET Salary = 25000
WHERE EmployeeId = 6

UPDATE EMPLOYEES_STAGE SET City = 'NYC'
WHERE EmployeeId = 5


SELECT * FROM EMPLOYEES_STAGE
SELECT * FROM EMPLOYEES

--we have to make both the tables the same
SET IDENTITY_INSERT EMPLOYEES ON--ENABLES YOU TO INSERT TO THE UNIQUE IDENTITY
SET IDENTITY_INSERT EMPLOYEES OFF

MERGE EMPLOYEES T 
	USING EMPLOYEES_STAGE s
	ON T.EmployeeId =S.EmployeeId

WHEN NOT MATCHED THEN 
	INSERT(EMPLOYEEID,EMPNAME,CITY,DEPARTMENT,SALARY ) 
	VALUES(S.EMPLOYEEID,S.EMPNAME,S.CITY,S.DEPARTMENT,S.SALARY)

WHEN MATCHED THEN 
	UPDATE SET T.CITY=S.CITY,
	T.DEPARTMENT=S.DEPARTMENT,
	T.SALARY=S.SALARY

WHEN NOT MATCHED BY SOURCE THEN
	DELETE;





