--PIVOT TRANSFORMS ROWS TO COLUMNS
SELECT * FROM
(SELECT CITY, Department,Salary FROM EMPLOYEES) T
PIVOT(SUM(Salary) FOR DEPARTMENT IN(IT,SALES))P

--UNPIVOT--TRANSFORMS COLUMNS TO ROWS
SELECT * INTO PIVOTDATA FROM
(SELECT CITY, Department,Salary FROM EMPLOYEES) T
PIVOT(SUM(Salary) FOR DEPARTMENT IN(IT,SALES))P

SELECT * FROM(
SELECT CITY,IT,SALES FROM PIVOTDATA) T
UNPIVOT(SALARY FOR DEPARTMENT IN (IT,SALES))U
