select * FROM EmployeeBk

SELECT FULLNAME, trim(LEFT(FULLNAME, CHARINDEX(' ',FULLNAME))) FirstName
FROM EmployeeBk

SELECT FULLNAME, 
RIGHT(FULLNAME,LEN(FULLNAME)- CHARINDEX(' ',FULLNAME,CHARINDEX(' ',FULLNAME)+1)) LastName
FROM EmployeeBk