---TEMP TABLES ARE STORED INSIDE THE SYSTEM DATABASES INSIDE THE DATABASE CALLED TEMPDB
--THEY HAVE THE FOLLOWING BENEFITS:
--CAN BE USED TO STORE TEMPORARY RESULTS

--CREATE TEMP TABLES
CREATE TABLE #EMPLOYEES(--IT WILL ALWAYS GO TO TEMPDB IF THERE IS A #
EMPID INT,
EMPNAME VARCHAR(100)
)
--REFER TI THE TABLE
SELECT * FROM #EMPLOYEES

--TWO TYPES OF TEMPTABLE
--LOCAL- CAN ONLY BE ACCESSED WITHIN THE SAME CONNECTION AS IT WAS CREATED. GET DROPPED AUTOMATICALLY WHEN YOU CLOSE THE WINDOW OR CONNECTION
--GLOBAL- ARE AVAILABLE ACROSS CONNECTION OR QUERY WINDOW


CREATE TABLE ##EMPLOYEES(--IT WILL ALWAYS GO TO TEMPDB IF THERE IS A #. THIS IS A GLOBAL TEMP TABLE
EMPID INT,
EMPNAME VARCHAR(100)
)

SELECT * INTO #Dimproduct FROM DimProduct

SELECT * FROM #Dimproduct