
CREATE TABLE TABLEA(Id INT)
CREATE TABLE TABLEB(Id INT)

INSERT INTO TABLEA VALUES(1),(1),(2),(NULL)
INSERT INTO TABLEB VALUES(1),(2),(NULL)

SELECT * FROM TABLEA
SELECT * FROM TABLEB

SELECT * FROM TABLEA A JOIN TABLEB B ON A.Id=B.Id

SELECT * FROM TABLEA A LEFT JOIN TABLEB B ON A.Id=B.Id

SELECT * FROM TABLEA A RIGHT JOIN TABLEB B ON A.Id=B.Id

SELECT * FROM TABLEA A FULL OUTER JOIN TABLEB B ON A.Id=B.Id

SELECT * FROM TABLEA A CROSS JOIN TABLEB B 




